server:
  port: 8080
  servlet:
    context-path: /springboot_mybatis

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ds_demo?useUnicode=true&characterEncoding=utf8&serverTimeZone=GMT%2B8
    username: root
    password: root

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      poll-interval: 3000
      quiet-period: 1000

  cache:
    ehcache:
      config: classpath:ehcache.xml

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: ga.hzcgw.springboot.po
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

logging:
  level:
    ga:
      hzcgw:
        springboot:
          dao: debug